#!/bin/bash
# register_job_device_mapper.sh — scan mapper .c files, generate
#                                map_job_to_device(), compile .so
#
# Usage:
#   ./scripts/register_job_device_mapper.sh               # generate + compile
#   ./scripts/register_job_device_mapper.sh --generate-only  # just generate
#
# Scans these directories for *.c files (each file = one mapper):
#   userconfig/job_device_mapper_examples/   (reference examples)
#   userconfig/your_job_device_mapper/       (user's own mappers, optional)
#
# Convention:
#   - File name mapper_<name>.c  →  function mapper_<name>()
#   - Signature: void mapper_<name>(device_map_ctx_t *ctx)
#   - Call device_map_add_entry() to register CPU/GPU bindings.
#
# Output:
#   - run_codes/benchmark-core/src/mapper_generated.c (generated dispatcher)
#   - bin/libs/libjob_device_mapper.so               (shared library)

set -euo pipefail
cd "$(dirname "$0")/.."  # project root (CCBench/)

MAPPER_DIRS=(
    userconfig/job_device_mapper_examples
    userconfig/your_job_device_mapper
)
GENERATED=run_codes/job_device_mapper/src/mapper_generated.c
COMPILE_ONLY="${1:-}"

# ---- Read selected_daemons from daemon config for filtering ----
DAEMON_CONFIG="userconfig/config_in_jsonc/daemon_config.jsonc"
SELECTED_DAEMONS=""
if [ -f "$DAEMON_CONFIG" ]; then
    # Extract the comma-separated list from "selected_daemons": "cpu, ib, ..."
    # Match the quoted JSON key (not comment text that merely mentions it),
    # then drop whitespace so the ",name," membership check below is exact.
    # `|| true`: an absent key makes grep exit 1, which would abort the whole
    # build under `set -euo pipefail` — an empty list is a valid config here.
    SELECTED_DAEMONS=$(grep '"selected_daemons"' "$DAEMON_CONFIG" 2>/dev/null | head -1 | \
                       sed 's/.*: *"\(.*\)".*/\1/' | tr -d ' ') || true
fi

# ---- Collect mapper files, check name collisions ----
declare -A mapper_seen  # name -> source file
FILES=""

for dir in "${MAPPER_DIRS[@]}"; do
    [ -d "$dir" ] || continue
    for f in "$dir"/mapper_*.c; do
        [ -f "$f" ] || continue

        name=$(basename "$f" .c)
        name="${name#mapper_}"  # "mapper_cpu" → "cpu"

        if [ -z "$name" ]; then
            echo "register_job_device_mapper.sh: error: malformed filename '$f'" >&2
            echo "  Expected pattern: mapper_<name>.c" >&2
            exit 1
        fi

        # Filter by selected_daemons (skip if name not in the configured list)
        if [ -n "$SELECTED_DAEMONS" ]; then
            if ! echo ",$SELECTED_DAEMONS," | grep -qi ",$name,"; then
                echo "register_job_device_mapper.sh: skipping mapper_${name} (not in selected_daemons: $SELECTED_DAEMONS)" >&2
                continue
            fi
        fi

        if [ -n "${mapper_seen[$name]:-}" ]; then
            echo "register_job_device_mapper.sh: error: mapper name collision: '$name'" >&2
            echo "  first:  ${mapper_seen[$name]}" >&2
            echo "  second: $f" >&2
            exit 1
        fi
        mapper_seen["$name"]="$f"
        FILES="$FILES $name:$f"
    done
done

if [ -z "$FILES" ]; then
    echo "register_job_device_mapper.sh: no mapper_*.c files found in:" >&2
    printf '  %s\n' "${MAPPER_DIRS[@]}" >&2
    echo "register_job_device_mapper.sh: generating empty stub anyway." >&2
fi

# Sort for deterministic output
FILES=$(echo "$FILES" | tr ' ' '\n' | sort)

echo "register_job_device_mapper.sh: generating $GENERATED ..." >&2
for entry in $FILES; do
    name="${entry%%:*}"
    src="${entry#*:}"
    echo "  mapper_${name}  ← $src" >&2
done

# ---- Generate mapper_generated.c ----
cat > "$GENERATED" << 'HEADER'
/* Generated by register_job_device_mapper.sh — do not edit manually. */
#include "job_device_mapper.h"

HEADER

# Forward declarations
for entry in $FILES; do
    name="${entry%%:*}"
    echo "void mapper_${name}(device_map_ctx_t *ctx);" >> "$GENERATED"
done
echo "" >> "$GENERATED"

# Dispatcher function
echo "void map_job_to_device(device_map_ctx_t *ctx) {" >> "$GENERATED"
if [ -n "$FILES" ]; then
    for entry in $FILES; do
        name="${entry%%:*}"
        echo "    mapper_${name}(ctx);" >> "$GENERATED"
    done
else
    echo "    (void)ctx;  /* no mappers registered */" >> "$GENERATED"
fi
echo "}" >> "$GENERATED"

echo "register_job_device_mapper.sh: done — $GENERATED" >&2

# ---- Compile .so ----
if [ "$COMPILE_ONLY" = "--generate-only" ]; then
    exit 0
fi

mkdir -p bin/libs

# Build source list: framework + generated file + all mapper .c files
FRAMEWORK_SRC="run_codes/benchmark-core/src/job_device_mapper.c"
SRC="$FRAMEWORK_SRC $GENERATED"
for entry in $FILES; do
    src="${entry#*:}"
    SRC="$SRC $src"
done

echo "register_job_device_mapper.sh: compiling bin/libs/libjob_device_mapper.so ..." >&2
gcc -O3 -Wall -Wextra -D_GNU_SOURCE \
    -I./run_codes/benchmark-core/include \
    -fPIC -shared \
    $SRC \
    -o bin/libs/libjob_device_mapper.so \
    -lm -ldl

echo "register_job_device_mapper.sh: done — bin/libs/libjob_device_mapper.so" >&2
