#!/bin/bash
# register_metrics.sh — scan metric .c files and generate deviation_metrics.c
#
# Usage:
#   ./scripts/register_metrics.sh               # generate + compile
#   ./scripts/register_metrics.sh --generate-only  # just generate, skip compile
#
# Scans these directories for *.c files (each file = one metric):
#   userconfig/deviation_metric_examples/   (reference examples)
#   userconfig/your_deviation_metrics/      (user's own metrics, optional)
#
# Convention:
#   - Filename without .c = registration name (e.g., "mse.c" → "mse")
#   - The file must contain ONE function named "compute_<name>"
#     with signature:
#       double compute_<name>(const void *buf1, const void *buf2,
#                             int count, data_type_t dtype)
#   - Extra params: read from env vars named METRIC_<UPPER_NAME>_<PARAM>

set -euo pipefail
cd "$(dirname "$0")/.."  # project root (CCBench/)

METRIC_DIRS=(
    userconfig/deviation_metric_examples
    userconfig/your_deviation_metrics
)
OUTPUT=run_codes/benchmark-core/src/deviation_metrics.c
COMPILE_ONLY="${1:-}"

# ---- Collect metric files (sorted), check name collisions ----
declare -A metric_seen  # name -> source file
FILES=""

for dir in "${METRIC_DIRS[@]}"; do
    [ -d "$dir" ] || continue
    for f in "$dir"/*.c; do
        [ -f "$f" ] || continue
        name=$(basename "$f" .c)

        if [ -n "${metric_seen[$name]:-}" ]; then
            echo "register_metrics.sh: error: metric name collision: '$name'" >&2
            echo "  first:  ${metric_seen[$name]}" >&2
            echo "  second: $f" >&2
            exit 1
        fi
        metric_seen["$name"]="$f"
        FILES="$FILES $f"
    done
done

if [ -z "$FILES" ]; then
    echo "register_metrics.sh: no metric .c files found in:" >&2
    printf '  %s\n' "${METRIC_DIRS[@]}" >&2
    exit 1
fi

# Sort alphabetically for stable bit positions
FILES=$(echo $FILES | tr ' ' '\n' | sort)

echo "register_metrics.sh: generating $OUTPUT from:" >&2
for f in $FILES; do echo "  $f" >&2; done

# ---- Generate deviation_metrics.c ----
cat > "$OUTPUT" <<'HEADER'
/* Generated by register_metrics.sh — do not edit manually. */
#include "validation.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

HEADER

# Forward declarations
for f in $FILES; do
    name=$(basename "$f" .c)
    echo "double compute_${name}(const void *buf1, const void *buf2, int count, data_type_t dtype);" >> "$OUTPUT"
done

echo "" >> "$OUTPUT"

# Implementations (copy-paste from each file)
for f in $FILES; do
    echo "/* ----- from $f ----- */" >> "$OUTPUT"
    cat "$f" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
done

# Registry
echo "/* Registry */" >> "$OUTPUT"
echo "metric_entry_t g_metric_registry[] = {" >> "$OUTPUT"
for f in $FILES; do
    name=$(basename "$f" .c)
    echo "    {\"${name}\", compute_${name}}," >> "$OUTPUT"
done
echo "};" >> "$OUTPUT"
echo "int g_metric_registry_count = sizeof(g_metric_registry) / sizeof(g_metric_registry[0]);" >> "$OUTPUT"

echo "register_metrics.sh: done — $OUTPUT" >&2

# ---- Compile validation.so ----
if [ "$COMPILE_ONLY" = "--generate-only" ]; then
    exit 0
fi

mkdir -p bin/libs
echo "register_metrics.sh: compiling bin/libs/validation.so ..." >&2
gcc -O3 -Wall -Wextra -I./run_codes/benchmark-core/include -fPIC -shared \
    run_codes/benchmark-core/src/validation.c "$OUTPUT" -o bin/libs/validation.so -lm
echo "register_metrics.sh: done — bin/libs/validation.so" >&2